sudo: required
language: python
git:
  depth: 10
  quiet: true
notifications:
  email:
    - tensorflow-datasets+travis@google.com
python:
  - "2.7"
  - "3.6"
env:
  matrix:
    - TF_VERSION="1.12.0"
    - TF_VERSION="1.13.0rc0"
    - TF_VERSION="tf-nightly"
    - TF_VERSION="tf2"
install:
  - ./oss_scripts/oss_pip_install.sh
script:
  - ./oss_scripts/oss_tests.sh
